### ISSUE TITLE
"./magento start" pending at: Setting up ca-certificates-java (20140324) ...

### ISSUE THREAD

**Issue by lazytyper** [andreaskoch/dockerized-magento#6]
I've been trying it on 2 different Ubuntu systems.
It's always pending with this:

```
Setting up openjdk-7-jre:amd64 (7u91-2.6.3-1~deb8u1) ...
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/policytool to provide /usr/bin/policytool (policytool) in auto mode
Setting up ca-certificates-java (20140324) ...
```

**Comment by andreaskoch** [comment]
I suspect that this message is from the Solr container build process.

It may happen from time to time that a docker image build fails if because of **installation resources are temporarily** (e.g. Java) unavailable at the Ubuntu download servers.

I've experienced similar issues in the past as well. But **right now** I have tested a project build from scratch and everything worked as expected. I have also tested it on Ubuntu - even though the host operating system should not have any influence on that.

Maybe you can try a full rebuild of all docker images for the project:

1. Clone the repository again
2. Pull the latest versions of all docker images used with `docker-compose pull`
3. Remove all previously built docker images (especially the `dockerizedmagento_solr` image)

	```bash
	docker images
	docker rmi dockerizedmagento_solr
	docker rmi dockerizedmagento_installer
	docker rmi dockerizedmagento_php
	```

4. Start the project `./magento start`



Please let me know if that fixes your problem.

**Comment by brandontamm** [comment]
I've tweaked and rebuilt this project several hundred times :) 

I've also seen the process hang at "ca-certificates" but there's never a rhyme or reason. I wouldn't worry about it. And the steps above have always worked the second time around.

**Comment by brandontamm** [comment]
@eschmid72 - Tagging you so you get notified. I've used Andreas' workaround several times and it works so if you are still stuck, try that and you should be able to close out the ticket :)

**Comment by eschmid72** [comment]
Thanks, it's working. But, I discovered one more little thing: I had to stop my local mysql + nginx services because the ports were needed. I thought the services would run on the virtual machine?

**Comment by brandontamm** [comment]
I may not be the most knowledgeable person to answer this, but the ports from the VM are mapped to the ports on your local machine so if they are currently being used that would cause a conflict. 
Change the ports on either your local machine or the VM (understanding that a VM change will more than likely include more in-depth changes to configuration files..)

**Comment by andreaskoch** [comment]
HI @lazytyper.
I am sorry I did not respond to your issue. I am closing it now because I believe this was a temporary docker issue. Sometimes the installers fail because of missing dependencies.

I have switched to pre-built images now and it should work just fine.

Greetings
 Andy
