### ISSUE TITLE
REST Api not working

### ISSUE THREAD

**Issue by Rishka** [andreaskoch/dockerized-magento#7]
Magento's rest api will not work with this image since oauth is not installed.

**Comment by brandontamm** [comment]
SOAP api is also not working for Sage Pay. I also have a Salesforce connector using SOAP api that I would assume won't work either.

I am going to attempt @Rishka fix and I will update if it works for extensions that use SOAP api as well.

**Comment by Rishka** [comment]
The fix should enable both SOAP versions and REST APIs.

**Comment by brandontamm** [comment]
Ahhhh - I found a bug and have tried several things to fix it ... looking for help.

@Rishka - REST API works because it doesn't use OpenSSL for authentication.

**Background:**
The installer container is built from php:5.6 and SOAP dependency was not installed
The php container is built from php:5.6-fpm and SOAP is installed.

**Problem:**
Not sure of the technicalities, but for whatever reason SOAP works on php container, but the installer container is not working and the conflict disables SOAP altogether :(

The code below was used to narrow the cause of the SOAP issue.. I built a file called testconnection.php and placed it in Magento root (code below.) Visiting http://www.URL.com/testconnection.php shows that SOAP works, as does running the following shell commands from the PHP container:
$ ./magento enter quickattach_php_1
$ php testconnection.php
$ openssl version -a
SOAP works at that point and the OpenSSL version is 

However, when you run those commands from the installer container (which doesn't have SOAP installed) you get a "Fatal error: Class 'SoapClient' not found in /var/www/html/web/testconnection.php on line 18"

<?php
$context = stream_context_create(array(
                'ssl' => array(
                    'verify_peer' => false,
                    'verify_peer_name' => false,
                    'allow_self_signed' => true
                )
            ));
$url = 'https://www.sagepayments.net/web_services/vterm_extensions/transaction_processing.asmx?WSDL';
try {
	$client = new SoapClient($url,array('stream_context' => $context));
	var_dump($client->__getFunctions());
} catch(exception $e) {
	echo $e->getMessage();
}

**What I Tried to fix:**
I added the soap extension to the installer container's docker file @ line 22 of 'docker-images/installer/Dockerfile'
      mcrypt \
      mysql \
      pdo_mysql \
+    soap \
      zip \
      && apt-get purge -y --auto-remove

After rebuilding project,  ($ docker-compose up ) showed an issue and I’m not sure how to fix it or what to do. 
.....
installer_1     | Fatal error: Call to a member function getRootCategoryPath() on array in /var/www/html/web/app/code/core/Mage/Catalog/Model/Resource/Url.php on line 738
installer_1     | Installing Sample Data: Admin User
.....

Although the store and functionality seem to work, the SOAP API still does not work. My error.log fills with errors (see pastebin @ http://pastebin.com/Kqh1DUuk)

I also ran ($ openssl version -a ) and noticed the 'php' and 'installer' containers were OpenSSL version 1.0.1k 8 Jan 2015, but my digital ocean node had outdated versions of OpenSSL version 1.0.1f 6 Jan 2014.

Any ideas?
